artifacts_root: artifacts   # Root folder where all project outputs will be saved

data_ingestion:             # Section for data ingestion config
  root_dir: artifacts/data_ingestion          # Folder to store raw and processed data
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip   # Link to dataset
  local_data_file: artifacts/data_ingestion/data.zip        # Where to save downloaded zip file
  unzip_dir: artifacts/data_ingestion                       # Where to extract data

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv  

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib
    